# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'q4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
import sys
from q5 import *

class Ui_q4(QtWidgets.QWidget):
    def __init__(self, name, count, total):
        super().__init__()
        self.name=name
        self.count=60
        self.total=total
    def setupUi(self, q4):
        q4.setObjectName("q4")
        q4.resize(638, 386)
        self.centralwidget = QtWidgets.QWidget(q4)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 70, 491, 126))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ques = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ques.setObjectName("ques")
        self.verticalLayout.addWidget(self.ques)
        self.r1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.r1.setObjectName("r1")
        self.verticalLayout.addWidget(self.r1)
        self.r2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.r2.setObjectName("r2")
        self.verticalLayout.addWidget(self.r2)
        self.r3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.r3.setObjectName("r3")
        self.verticalLayout.addWidget(self.r3)
        self.r4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.r4.setObjectName("r4")
        self.verticalLayout.addWidget(self.r4)
        self.push = QtWidgets.QPushButton(self.centralwidget)
        self.push.setGeometry(QtCore.QRect(50, 220, 71, 31))
        self.push.setStyleSheet("background-color: rgb(125, 121, 255);\n"
"border-color: rgb(0, 85, 127);\n"
"font: 75 9pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"")
        self.push.setObjectName("push")
        self.resume = QtWidgets.QPushButton(self.centralwidget)
        self.resume.setGeometry(QtCore.QRect(140, 220, 71, 31))
        self.resume.setStyleSheet("background-color: rgb(125, 121, 255);\n"
"border-color: rgb(0, 85, 127);\n"
"font: 75 9pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"")
        self.resume.setObjectName("resume")
        self.nextend = QtWidgets.QPushButton(self.centralwidget)
        self.nextend.setGeometry(QtCore.QRect(230, 220, 71, 31))
        self.nextend.setStyleSheet("background-color: rgb(125, 121, 255);\n"
"border-color: rgb(0, 85, 127);\n"
"font: 75 9pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"")
        self.nextend.setObjectName("nextend")
        self.Tlabel = QtWidgets.QLabel(self.centralwidget)
        self.Tlabel.setGeometry(QtCore.QRect(330, 40, 121, 20))
        self.Tlabel.setObjectName("timer")
        self.T2 = QtWidgets.QLineEdit(self.centralwidget)
        self.T2.setGeometry(QtCore.QRect(380, 40, 61, 20))
        self.T2.setStyleSheet("")
        self.T2.setObjectName("T2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 111, 20))
        self.label.setObjectName("label")
        self.T1 = QtWidgets.QLineEdit(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(100, 40, 91, 20))
        self.T1.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.T1.setObjectName("T1")
        q4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(q4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 18))
        self.menubar.setObjectName("menubar")
        q4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(q4)
        self.statusbar.setObjectName("statusbar")
        q4.setStatusBar(self.statusbar)
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.ShowTime)
        self.timer.start(1000)
        self.retranslateUi(q4)
        QtCore.QMetaObject.connectSlotsByName(q4)

    def retranslateUi(self, q4):
        _translate = QtCore.QCoreApplication.translate
        q4.setWindowTitle(_translate("q4", "screen2q4"))
        self.ques.setText(_translate("q4", "4. Which of the following is the correct extension of the Python file?"))
        self.r1.setText(_translate("q4", "a) .python"))
        self.r2.setText(_translate("q4", "b) .pl"))
        self.r3.setText(_translate("q4", "c) .py"))
        self.r4.setText(_translate("q4", "d) .p"))
        self.push.setText(_translate("q4", "Pause"))
        self.resume.setText(_translate("q4", "Resume"))
        self.nextend.setText(_translate("q4", "Next"))
        self.Tlabel.setText(_translate("q4", "TIMER"))
        self.label.setText(_translate("q4", "NAME"))
        self.nextend.clicked.connect(self.opques)
        self.nextend.clicked.connect(q4.close)
    def ShowTime(self):
        if self.count > 0:
            self.count = self.count - 1
        S1 = str(self.count // 60)
        S2 = str(self.count % 60)
        S3 = S1 + "." + S2
        self.T1.setText(str(self.name))
        self.T2.setText(str(S3))
    def opques(self):

        if self.r3.isChecked() == True:
            self.total = self.total + 1

        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_q5(self.name, self.count, self.total)
        self.ui.setupUi(self.queswin)
        self.queswin.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    q4 = QtWidgets.QMainWindow()
    ui = Ui_q4()
    ui.setupUi(q4)
    q4.show()
    sys.exit(app.exec_())
