# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from q1 import *

class Ui_homewin(object):
    def setupUi(self, homewin):
        homewin.setObjectName("homewin")
        homewin.resize(661, 351)
        self.centralwidget = QtWidgets.QWidget(homewin)
        self.centralwidget.setObjectName("centralwidget")
        self.view = QtWidgets.QPushButton(self.centralwidget)
        self.view.setGeometry(QtCore.QRect(290, 220, 81, 41))
        self.view.setStyleSheet("background-color: rgb(125, 121, 255);\n"
"border-color: rgb(0, 85, 127);\n"
"font: 75 9pt \"Arial\";\n"
"color:rgb(255, 255, 255);")
        self.view.setObjectName("view")
        self.startquiz = QtWidgets.QPushButton(self.centralwidget)
        self.startquiz.setGeometry(QtCore.QRect(270, 160, 121, 41))
        self.startquiz.setStyleSheet("background-color: rgb(125, 121, 255);\n"
"selection-color: rgb(205, 223, 255);\n"
"selection-background-color: rgb(205, 223, 255);\n"
"border-color: rgb(0, 85, 127);\n"
"font: 75 9pt \"Arial\";\n"
"color:rgb(255, 255, 255);")
        self.startquiz.setObjectName("startquiz")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 100, 211, 20))
        self.label.setObjectName("label")
        self.T1 = QtWidgets.QLineEdit(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(310, 100, 131, 21))
        self.T1.setObjectName("T1")
        homewin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(homewin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 18))
        self.menubar.setObjectName("menubar")
        homewin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(homewin)
        self.statusbar.setObjectName("statusbar")
        homewin.setStatusBar(self.statusbar)

        self.retranslateUi(homewin)
        QtCore.QMetaObject.connectSlotsByName(homewin)

    def retranslateUi(self, homewin):
        _translate = QtCore.QCoreApplication.translate
        homewin.setWindowTitle(_translate("homewin", "screen1"))
        self.view.setText(_translate("homewin", "VIEW"))
        self.startquiz.setText(_translate("homewin", "START QUIZ"))
        self.label.setText(_translate("homewin", "ENTER YOUR NAME:"))
        self.startquiz.clicked.connect(self.opques)
        self.startquiz.clicked.connect(homewin.close)

    def opques(self):
        self.S1 = self.T1.text()
        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_q1(self.S1)
        self.ui.setupUi(self.queswin)
        self.queswin.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homewin = QtWidgets.QMainWindow()
    ui = Ui_homewin()
    ui.setupUi(homewin)
    homewin.show()
    sys.exit(app.exec_())
